#!/bin/bash

exe_path="../build/default/AoC2023 day2b"
comparison_result_path="functionalTests/expectedResults.txt"
output_path="output.txt"

# Guarantee that the output will be the one generated by the script
if [ -e $output_path ]; then
    rm $output_path
fi

# Verify if the comparison result file exists
if [ ! -e $comparison_result_path ]; then
    echo "Comparison result file doesn't exist (" $comparison_result_path ")"
    exit 1  
fi 

# Execute code 
echo $($exe_path) > $output_path
execution_result=$?

# Verify if app was properly executed 
if [ $execution_result -ne 0 ]; then
    echo "Execution didn't run as expected (" $execution_result ")"
    exit 2
fi 

# Verify if the files are the same
if cmp $comparison_result_path $output_path; then
    echo "Tests passed"
    exit 0
fi

# test fail
echo "Test output is not the same"
exit 3
